export const BOOKS = [
  'All 6-Books 2025',
  'Holiness Everyday',
  'Charismatic Ministry - Ministry Gifts and More (Volume 4)',
  'Baptism',
  'Praying Always: Every Day',
  'One Flesh',
  'Women Pastors; Why the controversy?',
  'Tree of the Knowledge of good and Evil',
  'God who became Jesus',
  'Healing everyday',
  'Leading of the Spirit Everyday',
  'Walking in Love everyday',
  'Walking in the Spirit everyday',
  'Fellowship in the local Church',
  'Why Tongues',
  'Revelation Knowledge',
  'Rise and be Healed',
  'Myth of Unanswered Prayers',
  'Fire of the Holy Ghost',
];

export const BOOKS_LIST = [
  {
    title: 'All 6-Books 2025',
    brand: 'LWM',
    model: 'BC001',
    price: '₦35,000',
    url: 'https://lwmbooks.com/all-books/all-discounted-books-(6)',
    books_included: [
      'Holiness Everyday',
      'Praying Always',
      'Charismatic Ministry - Ministry Gifts and More (Volume 4)',
      'Baptism',
      'One Flesh',
      'Women Pastors; Why the controversy?',
    ],
  },
  {
    title: 'Holiness Everyday',
    brand: 'LWM',
    model: 'BC002',
    price: '₦2,000',
    url: 'https://lwmbooks.com/all-books/holiness-everyday',
  },
  {
    title: 'Charismatic Ministry - Ministry Gifts and More (Volume 4)',
    brand: 'LWM',
    model: 'BC003',
    price: '₦15,000',
    url: 'https://lwmbooks.com/all-books/charismatic-ministry-ministry-gifts-and-more-(volume-4)',
  },
  {
    title: 'Baptism',
    brand: 'LWM',
    model: 'BC004',
    price: '₦12,000',
    url: 'https://lwmbooks.com/all-books/baptism',
  },
  {
    title: 'Praying Always: Every Day',
    brand: 'LWM',
    model: 'BC005',
    price: '₦2,000',
    url: 'https://lwmbooks.com/all-books/praying-always:-every-day',
  },
  {
    title: 'One Flesh',
    brand: 'LWM',
    model: 'BC005',
    price: '₦3,000',
    url: 'https://lwmbooks.com/all-books/one-flesh',
  },
  {
    title: 'Women Pastors; Why the controversy?',
    brand: 'LWM',
    model: 'BC007',
    price: '₦3,000',
    url: 'https://lwmbooks.com/all-books/women-pastors;-why-the-controversy',
  },
  {
    title: 'Tree of the Knowledge of good and Evil',
    brand: 'LWM',
    model: 'CCM-001',
    price: '₦15,000',
    url: 'https://lwmbooks.com/all-books/tree-of-the-knowledge-of-good-and-evil',
  },
  {
    title: 'God who became Jesus',
    brand: 'LWM',
    model: '2024-01',
    price: '₦15,000',
    url: 'https://lwmbooks.com/all-books/god-who-became-jesus',
  },
  {
    title: 'Healing everyday',
    brand: 'LWM',
    model: '019',
    price: '₦2,000',
    url: 'https://lwmbooks.com/all-books/healing-everyday',
  },
  {
    title: 'Leading of the Spirit Everyday',
    brand: 'LWM',
    model: '017',
    price: '₦2,000',
    url: 'https://lwmbooks.com/all-books/leading-of-the-spirit-everyday',
  },
  {
    title: 'Walking in Love everyday',
    brand: 'LWM',
    model: '016',
    price: '₦2,000',
    url: 'https://lwmbooks.com/all-books/walking-in-love-everyday',
  },
];
